{{- if not .Values.target.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-import.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database-import.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.databases.ysql.password | default "" | b64enc }}
  cassandra-password: {{ .Values.databases.ycql.password | default "" | b64enc }}
  janusgraph-password: {{ .Values.databases.janusgraph.password | default "" | b64enc }}
  elasticsearch-password: {{ .Values.databases.elasticsearch.password | default "" | b64enc }}
  {{- if .Values.dbFixups.keycloakCredentials.enabled }}
  keycloak-admin-password: {{ .Values.dbFixups.keycloakCredentials.adminPassword | default "" | b64enc }}
  {{- end }}
{{- end }}
