apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: common
  repository: https://nimbushubin.github.io/helmcharts
  version: 0.1.0
description: A production-ready Helm chart for Lern Service
maintainers:
- name: Sunbird
name: lern
version: 0.1.0
