# Default values for obsrvbb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullname: edbb
replicaCount: 1
devops_release_branch: release-7.0.0

provisioningAnnotations: &provisioningAnnotations
  "helm.sh/hook-weight": "-4"
    # "helm.sh/hook": post-install,post-upgrade

kafka: &kafka
  enabled: true
  nameOverride: kafka
  fullnameOverride: kafka
  clientProtocol: PLAINTEXT
  host: kafka
  port: 9092
  image:
    registry: sunbirded.azurecr.io
    repository: kafka
    tag: 3.3.1-debian-11-r25
  persistence:
    size: 25Gi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 5
    failureThreshold: 10
    periodSeconds: 30
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations
    replicationFactor: 1
    numPartitions: 1
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 750m
      memory: 1024Mi
  listeners:
    client:
      protocol: PLAINTEXT
  controller:
      protocol: PLAINTEXT
  interbroker:
      protocol: PLAINTEXT
  external:
      protocol: PLAINTEXT
  sasl:
    enabledMechanisms: "PLAIN"
    interBrokerMechanism: "PLAIN"
    controllerMechanism: "PLAIN"
  tls:
    autoGenerated:
      enabled: false
    existingSecret: ""

knowledgemw:
  opa_enabled: false

migration:
  yugabyte:
    waitTime: 120

nginx-private-ingress:
  enabled: false

redis: &redis
  enabled: false
  registry: "sunbirded.azurecr.io"
  repository: "redis"
  replica:
    replicaCount: 0
  nameOverride: "redis"
  fullnameOverride: "redis"
  auth:
    enabled: false
  host: "redis-master"
  port: 6379
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  master:
    persistence:
      size: 25Gi
    primary:
    resources:
      limits:
        cpu: 0.5
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 1Gi 

router:
  enabled: false

secor:
  enabled: true
  serviceAccount:
    create: false

yugabyte: &yugabyte
  enabled: true
  nameOverride: "yugabyte"
  fullnameOverride: "yugabyte"
  host: "yb-tserver-service" 
  port: 9042
  postgresql_port: 5433
  databases:
      - name: "kong"
      - name: "superset"
      - name: "registry"
      - name: "portal"
      - name: "sunbird"
  gflags:
    tserver: 
      cdc_enable_replicate_intents: "true"    
      ysql_enable_read_committed_isolation: "true"
  image:
    registry: yugabytedb
    repository: yugabyte
    tag: 2025.2.0.0-b131 
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations
  # Force single replica for Yugabyte masters and tservers (override subchart defaults)
  replicas:
    master: 3
    tserver: 3
  username: "yugabyte"
  password: "yugabyte"  

nginx-public-ingress:
  enabled: true

echo:
  enabled: true

player:
  enabled: true

kong:
  enabled: true

kong-apis:
  enabled: true

kong-consumers:
  enabled: true

knowledgemw:
  enabled: true

global:
  kafka: *kafka
  keycloak_key_configmap: keycloak-key
  keycloak_kid_keys_configmap: keycloak-kids-keys
  kong_desktop_device_consumer_names_for_opa: '["portal", "desktop"]'
  redis: *redis
  yugabyte: *yugabyte