# Dockerfile to build a custom JanusGraph image with your JAR
FROM bitnamilegacy/janusgraph:1.1.0-debian-12-r21

# Copy your JAR into the JanusGraph lib directory
COPY config/janusgraph-cdc-extension-1.0.0.jar /opt/bitnami/janusgraph/lib/


