input {
  file {
    start_position => "beginning"
    type => "graph_event"
    path => ["/opt/bitnami/janusgraph/logs/cdc-events.log"]
    sincedb_path => "/usr/share/logstash/.sincedb_janusgraph_cdc"
  }
}
filter {
  grok {
    match => [
      "message",
      "%{TIMESTAMP_ISO8601:log_ts} %{DATA:log_prefix} message=%{GREEDYDATA:json_payload}"
    ]
  }
  json {
    source => "json_payload"
  }
}

output {
  kafka {
    bootstrap_servers => "{{ .Values.global.kafka.host }}:{{ .Values.global.kafka.port }}"
    topic_id => "{{ .Values.global.env }}.knowlg.learning.graph.events"
    message_key => "%{nodeUniqueId}"
    codec => plain {
      format => "%{json_payload}"
    }
  }
}
