input {
  file {
    start_position => "beginning"
    type => "graph_event"
    path => ["/opt/bitnami/janusgraph/logs/cdc-events.log"]
    sincedb_path => "/opt/bitnami/janusgraph/logs/.sincedb_janusgraph_cdc"
  }
}
filter {
  grok {
    match => [
      "message",
      "%{TIMESTAMP_ISO8601:log_ts} %{DATA:log_prefix} message=%{GREEDYDATA:json_payload}"
    ]
  }
  json {
    source => "json_payload"
  }
}

output {
  kafka {
    bootstrap_servers => "{{ .Values.global.kafka.host }}:{{ .Values.global.kafka.port }}"
    topic_id => "{{ .Values.global.env }}.knowlg.learning.graph.events"
    message_key => "%{nodeUniqueId}"
    codec => plain {
      format => "%{json_payload}"
    }
    client_dns_lookup => "use_all_dns_ips"
    retries => 2147483647
    retry_backoff_ms => 100
    reconnect_backoff_ms => 3000
    request_timeout_ms => 30000
    metadata_max_age_ms => 60000
  }
}
