# Sync Tool Configuration

# Graph
graph.passport.key.base="{{ .Values.global.graph_passport.key_base }}"
graph.storage.backend="cql"
graph.storage.hostname="{{ .Values.global.yugabyte.host }}"
graph.storage.port="{{ .Values.global.yugabyte.port }}"
graph.graphId="domain"

# Route (required by DriverUtil)
route.all="bolt://{{ .Values.global.janusgraph.host }}:{{ .Values.global.janusgraph.port }}"
route.bolt.write.domain="bolt://{{ .Values.global.janusgraph.host }}:{{ .Values.global.janusgraph.port }}"

# OpenSearch
search.es_conn_info="{{ .Values.global.opensearch.host }}:{{ .Values.global.opensearch.port }}"
search.es_scheme="http"
compositesearch.index.name="compositesearch"

# Sync config
sync {
    batchSize = 200
    retryCount = 3

    nested.fields = ["badgeAssertions", "targets", "badgeAssociations", "me_totalTimeSpent", "me_totalPlaySessionCount", "me_totalTimeSpentInSec", "me_totalDialcode", "provider", "osMetadata", "actions", "batches", "credentials", "plugins", "trackable"]

    string.only.fields = ["interceptionPoints", "editorState", "variants", "timeLimits", "contentTypesCount", "mimeTypesCount", "lhs_options", "rhs_options", "options", "answer", "reservedDialcodes", "issuer", "signatoryList", "data"]

    ignored.fields = ["responseDeclaration", "body", "oldBody", "stageIcons", "screenshots", "externallink", "hierarchy", "relational_metadata", "instructions", "hints", "media", "interactions", "outcomeDeclaration", "graphId"]

    restrict.objectTypes = ["EventSet", "Questionnaire", "Misconception", "FrameworkType", "Event"]
}
