{{- if .Values.global.openai_api_key }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.global.openai_api_key | b64enc | quote }}
{{- end }}
