# Azure Container Details
azure_account: "{{ .Values.global.cloud_storage_access_key }}"
azure_secret: ""
azure_container_name: "{{ .Values.global.private_container_name }}"


s3_access_key: ""
s3_secret_id: ""
s3_region: ""
s3_endpoint: ""
s3_path_style_access: false
s3_bucket_name: "telemetry-data-store"
timezone: "UTC"
jvm_memory: "1024m"

gcp_bucket_name: "telemetry-data-store"


storage_type: "s3"
storageClass: ""

kafka: &kafka
  host: "{{ .Values.global.kafka.host }}"
  port: "{{ .Values.global.kafka.port }}"

base_path: "telemetry-data"

base_config: &base_config
  enabled: true
  replicas: 1
  service_name: "telemetry-ingest-backup"
  timestamp_key: "syncts"
  fallback_timestamp_key: "@timestamp"
  kafka_broker_host: "{{ .Values.global.kafka.host }}"
  max_file_size: "100000000"
  max_file_age: "120"
  partition_prefix_enabled: "false"
  partition_prefix_key: "nil"
  partition_prefix_mapping: "{}"
  message_channel_identifier: "nil"
  output_file_pattern: "{partition}-{currentTimestamp}.json"
  message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  storage:
    size: 10Gi
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 500Mi
  lag_threshold_warning: 50000
  lag_threshold_critical: 100000

secor_jobs:
  telemetry-ingest-backup:
    <<: *base_config
    base_path: "telemetry-data-store/telemetry/ingest"
    topic: "{{ .Values.global.env }}.telemetry.ingest"
    consumer_group: "{{ .Values.global.env }}-telemetry-ingest-backup"

namespace: ""

repository: secor
tag: 1.0.0-GA
imagePullPolicy: IfNotPresent
imagePullSecrets: []

exporter:
  image:
    repository: prom/statsd-exporter
    tag: latest
    pullPolicy: IfNotPresent

prometheus_rule_selector_app: prometheus-operator
prometheus_rule_selector_release: prometheus-operator

# If you enable this, secor lag alert rules will be created in the flink cluster.
# In our case the consumer group lag metrics available in core prometheus.
# So we need to create the secor lag alert rule in core prometheus.
# By adding this condition we are avoiding creating the secor lag alert rule in flink cluster.
alertrules:
  enabled: false

# This condition is whether to create the secor lag alert rule or not.
secor_alertrule:
  enabled: false


commonAnnotations:
    "helm.sh/hook-weight": "-5"

persistence:
  existingClaim: ""

nodeSelector:

setPvOwnership:
  enabled: true

serviceAccount:
  create: false