{{- if not .Values.source.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-export.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database-export.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.databases.postgresql.password | default "" | b64enc }}
  cassandra-password: {{ .Values.databases.cassandra.password | default "" | b64enc }}
  neo4j-password: {{ .Values.databases.neo4j.password | default "" | b64enc }}
  elasticsearch-password: {{ .Values.databases.elasticsearch.password | default "" | b64enc }}
{{- end }}
