{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.workload_identity_service_account_name | default "workload-identity" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if eq .Values.global.cloud_storage_provider "azure" }}
    azure.workload.identity/client-id: {{ .Values.global.azure_client_id | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
