---
kong_apis:

- name: createGroup
  uris: "{{ .Values.group_service_prefix }}/v1/create"
  url: "{{ .Values.group_service_url }}/v1/group/create"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"


- name: updateGroup
  uris: "{{ .Values.group_service_prefix }}/v1/update"
  url: "{{ .Values.group_service_url }}/v1/group/update"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupUpdate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"


- name: listGroup
  uris: "{{ .Values.group_service_prefix }}/v1/list"
  url: "{{ .Values.group_service_url }}/v1/group/list"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"


- name: readGroup
  uris: "{{ .Values.group_service_prefix }}/v1/read"
  url: "{{ .Values.group_service_url }}/v1/group/read"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"


- name: deleteGroup
  uris: "{{ .Values.group_service_prefix }}/v1/delete"
  url: "{{ .Values.group_service_url }}/v1/group/delete"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupAdmin
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"


- name: updateGroupMembership
  uris: "{{ .Values.group_service_prefix }}/membership/v1/update"
  url: "{{ .Values.group_service_url }}/v1/group/membership/update"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - groupUpdate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.small_request_size_limit }}"

- name: getDiscussionTagsList
  uris: "{{ .Values.discussions_prefix }}/tags"
  url: "{{ .Values.discussions_mw_service_url }}/tags"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getDiscussionCategories
  uris: "{{ .Values.discussions_prefix }}/categories"
  url: "{{ .Values.discussions_mw_service_url }}/categories"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getDiscussionNotificationsList
  uris: "{{ .Values.discussions_prefix }}/notifications"
  url: "{{ .Values.discussions_mw_service_url }}/notifications"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getUserDetailsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/user"
  url: "{{ .Values.discussions_mw_service_url }}/user"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getCategoryDetailsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/category"
  url: "{{ .Values.discussions_mw_service_url }}/category"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getUnreadTopicsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/unread"
  url: "{{ .Values.discussions_mw_service_url }}/unread"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getRecentTopicsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/recent"
  url: "{{ .Values.discussions_mw_service_url }}/recent"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getPopularTopicsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/popular"
  url: "{{ .Values.discussions_mw_service_url }}/popular"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getTopTopicsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/top"
  url: "{{ .Values.discussions_mw_service_url }}/top"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getTopicsOfDiscussionById
  uris: "{{ .Values.discussions_prefix }}/topic"
  url: "{{ .Values.discussions_mw_service_url }}/topic"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getTotalUnreadTopicsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/unread/total"
  url: "{{ .Values.discussions_mw_service_url }}/unread/total"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getTopicsOfDiscussionByTeaserId
  uris: "{{ .Values.discussions_prefix }}/topic/teaser"
  url: "{{ .Values.discussions_mw_service_url }}/topic/teaser"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getTopicsPaginationByIdOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/topic/pagination"
  url: "{{ .Values.discussions_mw_service_url }}/topic/pagination"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getGroupsListOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/groups"
  url: "{{ .Values.discussions_mw_service_url }}/groups"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getRecentPostsByDateOfDiscussions
  uris: "{{ .Values.discussions_prefix }}/recent/posts"
  url: "{{ .Values.discussions_mw_service_url }}/recent/posts"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: createTopicOfDiscussions
  uris: "{{ .Values.discussions_prefix }}/v2/topics"
  url: "{{ .Values.discussions_mw_service_url }}/v2/topics"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: createCategoryOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/v2/categories"
  url: "{{ .Values.discussions_mw_service_url }}/v2/categories"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: createGroupsOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/v2/groups"
  url: "{{ .Values.discussions_mw_service_url }}/v2/groups"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: createNewPostOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/v2/posts"
  url: "{{ .Values.discussions_mw_service_url }}/v2/posts"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: createNewUserOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/v2/users"
  url: "{{ .Values.discussions_mw_service_url }}/v2/users"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getUserDetailsByUsername
  uris: "{{ .Values.discussions_prefix }}/user/username"
  url: "{{ .Values.discussions_mw_service_url }}/user/username"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: getForumIdOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/forumId"
  url: "{{ .Values.discussions_mw_service_url }}/forumId"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionAccess
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: addForumOfDiscussion
  uris: "{{ .Values.discussions_prefix }}/forum"
  url: "{{ .Values.discussions_mw_service_url }}/forum"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"


- name: copyPrivilegesFromParentCategory
  uris: "{{ .Values.discussions_prefix }}/privileges/v2/copy"
  url: "{{ .Values.discussions_mw_service_url }}/privileges/v2/copy"
  strip_path: true
  plugins:
  - name: jwt
  - name: cors
  - {{ .Values.statsd_pulgin | toYaml | nindent 4 | trim }}
  - name: acl
    config.allow:
    - discussionCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ .Values.medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ .Values.medium_request_size_limit }}"